Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
from datetime import datetime

import ase
import ase.io
import numpy as np
import click

import ShiftML2 as sml
import time
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [1], line 9[0m
[0;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mclick[39;00m
[1;32m----> 9[0m [38;5;28;01mimport[39;00m [38;5;21;01mShiftML2[39;00m [38;5;28;01mas[39;00m [38;5;21;01msml[39;00m
[0;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mtime[39;00m

File [1;32mC:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\ShiftML2\__init__.py:1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mShiftML2[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m

File [1;32mC:\ProgramData\Anaconda3\envs\SMLv2\lib\site-packages\ShiftML2\ShiftML2.py:16[0m
[0;32m     13[0m [38;5;28;01mimport[39;00m [38;5;21;01mcopy[39;00m
[0;32m     15[0m [38;5;28;01mimport[39;00m [38;5;21;01mrascal[39;00m
[1;32m---> 16[0m [38;5;28;01mimport[39;00m [38;5;21;01mrascal[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrepresentations[39;00m [38;5;28;01mas[39;00m [38;5;21;01mrep[39;00m
[0;32m     18[0m [38;5;66;03m# Setting the model directory[39;00m
[0;32m     19[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m(os[38;5;241m.[39mpath[38;5;241m.[39mdirname(os[38;5;241m.[39mpath[38;5;241m.[39mabspath([38;5;18m__file__[39m)) [38;5;241m+[39m [38;5;124m"[39m[38;5;124m/model_dir.txt[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mr[39m[38;5;124m"[39m) [38;5;28;01mas[39;00m F:

[1;31mModuleNotFoundError[0m: No module named 'rascal.representations'
ModuleNotFoundError: No module named 'rascal.representations'

